Example file endpoint returning a bandgap prediction
  ---
  parameters:
    - name: input_file
      in: formData
      type: file
      required: true
      description: Bandgap File 
  responses:
    500:
      description: Error Please enter the correct input file
    200:
      description: Model Details for multiple prediction by passing input file as parameter
